version: '3.9'

services:
  database:
    image: postgres:13
    container_name: test
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=jhon
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgresql-volume:/var/lib/postgresql/data

volumes:
  postgresql-volume:
    external: true
